spring:
  application:
    name: bankapp

  datasource:
    url: jdbc:postgresql://ledger.c302gk4uasl6.us-west-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: RDSLedgerDataBase24$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    org.springframework.security.authentication: error

